---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

## Subset of Instacart Data

```{r}
data("instacart")
```

```{r}
instacart_subset = 
instacart %>% 
  mutate(mean_hour = mean(order_hour_of_day)) %>%
  select(product_name, order_dow, order_hour_of_day, aisle, department, mean_hour) %>% 
  mutate(
    order_dow = 
      recode_factor(order_dow, "0" = "Monday", "1" = "Tuesday", "2" = "Wednesday", "3" = "Thursday", "4" = "Friday", "5" = "Saturday", "6" = "Sunday"))
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart_subset %>% 
  filter(
    department == "produce"
  ) %>% 
  count(product_name) %>% 
  plot_ly(
    x = ~product_name, y = ~n, type = "scatter", mode = "markers")
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart_subset %>% 
  plot_ly(y = ~department, color = ~order_dow, type = "box", colors = "viridis")
```


### Chart C

```{r}
instacart_subset %>% 
  count(aisle) %>% 
  filter(n > 20000) %>% 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar", colors = "viridis")
```

